### ISSUE TITLE
测试了四个盘，三个盘外链放入网站无法显示

### ISSUE THREAD

**Issue by kevinliu2046** [qkqpttgf/OneManager-php#176]
您好，我分别搭建了四个盘，两个oneindex，两个onemanager
1、oneindex
一个用的免费空间，一个CF workers，CF的外链正常，套cdn.rawgit.org加速也正常，而空间二级域名的外链无法显示，套CDN加速也不行，放入浏览器地址栏显示The requested URL was not found on this server
2、onemanager
搭建在两个不同的空间商，两个都不能外链，
其中一个之前搭过oneindex（之前外链正常，套images.weserv.nl加速正常），重新搭建onemanager后也出现外链无法显示，套CDN同样显示The requested URL was not found on this server
请问怎么解决？盼复，谢谢

**Comment by qkqpttgf** [comment]
这问题白问了，你都不知道你在说什么。
完全不知道你的症状在哪。

**Comment by kevinliu2046** [comment]
> 这问题白问了，你都不知道你在说什么。
> 完全不知道你的症状在哪。

小白一个，刚搭建网盘没多久，我现在就是不知道症状在哪里？只能描述表面情况，搭建都是按照教程走的

**Comment by kevinliu2046** [comment]
套另一个CDN显示的有错误代码，您看看有用吗？
java.lang.IllegalStateException: [GET http://relay.jare.io/?u=*****.jpg] failed in 0ms: null
	at org.takes.facets.fallback.TkFallback.error(TkFallback.java:234)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:115)
	at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:54)
	at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:66)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.fork.FkHost$1.route(FkHost.java:81)
	at org.takes.facets.fork.FkWrap.route(FkWrap.java:61)
	at org.takes.facets.fork.FkChain.route(FkChain.java:75)
	at org.takes.facets.fork.TkFork.act(TkFork.java:100)
	at org.takes.facets.forward.TkForward.act(TkForward.java:68)
	at org.takes.facets.fork.FkFixed$1.route(FkFixed.java:56)
	at org.takes.facets.fork.FkWrap.route(FkWrap.java:61)
	at org.takes.facets.fork.FkChain.route(FkChain.java:75)
	at org.takes.facets.fork.TkFork.act(TkFork.java:100)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:91)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:86)
	at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:54)
	at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:66)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.flash.TkFlash.act(TkFlash.java:108)
	at org.takes.tk.TkMeasured$1.act(TkMeasured.java:67)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkVersioned$1.act(TkVersioned.java:73)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:71)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.http.BkBasic.print(BkBasic.java:108)
	at org.takes.http.BkBasic.accept(BkBasic.java:84)
	at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
	at org.takes.http.BkWrap.accept(BkWrap.java:52)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:89)
	at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException

**Comment by kevinliu2046** [comment]
用了heroku搭建，一切正常，谢谢

**Comment by Posuomen** [comment]
> 用了heroku搭建，一切正常，谢谢

我也遇到这个问题，一个盘正常，两个盘就不行了。
